packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  # Build tools
  turbo: ^2.4.4
  prettier: ^3.5.3
  lefthook: ^1.11.5

  # TypeScript
  typescript: ^5.7.3

  # React / Next.js
  react: ^19.0.0
  react-dom: ^19.0.0
  next: ^15.2.1
  "@types/react": ^19.0.10
  "@types/react-dom": ^19.0.4

  # Styling
  tailwindcss: ^4.0.9
  "@tailwindcss/postcss": ^4.0.9

  # Database
  drizzle-orm: ^0.39.3
  drizzle-kit: ^0.30.4
  better-sqlite3: ^11.8.1
  "@types/better-sqlite3": ^7.6.13

  # Validation
  zod: ^3.24.2

  # Testing
  vitest: ^3.0.5
  "@vitest/coverage-v8": ^3.0.5
  "@testing-library/react": ^16.2.0
  "@testing-library/jest-dom": ^6.6.3
  "@playwright/test": ^1.50.1
  jsdom: ^26.0.0

  # Linting
  eslint: ^9.20.0
  "@eslint/js": ^9.20.0
  typescript-eslint: ^8.24.0
  eslint-plugin-react-hooks: ^5.1.0
  eslint-config-next: ^15.2.1
  eslint-config-prettier: ^10.0.1
  globals: ^15.15.0
